project1/diary/urls.py
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'), #/diary
    path('add/', views.AddView.as_view(), name='add'), #/diary/add
    path('update/<int:pk>/',views.UpdateView.as_view(), name='update'), #diary/update/1
    path('delete/<int:pk>/',views.DeleteView.as_view(), name='delete'), #/diary/delete/1
    path('detail/<int:pk>/',views.DetailView.as_view(), name='detail'), #/diary/detail/1
]

project1/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),
]

project1/diary/models.py
from django.db import models
from django.utils import timezone


class Day(models.Model):
    title = models.CharField('タイトル',max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付',default=timezone.now)

    def __str__(self):
        return self.title

project1/diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields='__all__'

project1/diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day


class IndexView(generic.ListView):
    model = Day
    paginate_by = 3



class AddView(LoginRequiredMixin,generic.CreateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')


class UpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')


class DeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index')


class DetailView(generic.DetailView):
    model = Day

project1/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
      <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block extracss %}{% endblock %}
  </head>
  <body>
      <div class="container">
      <nav class="nav">
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
        {% if user.is_superuser %}
        <a class="nav-link" href="{% url 'diary:add' %}" target="_blank">追加</a>
        {% endif %}
      </nav>
    {% block content %}
    {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
</body>
</html>

project1/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
<table class="table">
    <tr>
        <th>タイトル</th>
        <td>{{ day.title }}</td>
    </tr>
    <tr>
        <th>本文</th>
        <td>{{ day.text }}</td>
    </tr>
    <tr>
        <th>日付</th>
        <td>{{ day.date }}</td>
    </tr>
</table>
<p>こちらのデータを削除します</p>
<button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

project1/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
    <tr>
        <th>タイトル</th>
        <td>{{ day.title }}</td>
    </tr>
    <tr>
        <th>本文</th>
        <td>{{ day.text | linebreaksbr }}</td>
    </tr>
    <tr>
        <th>日付</th>
        <td>{{ day.date }}</td>
    </tr>
</table>
{% endblock %}

project1/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<p>{{ day.title }}</p>
<form action="" method="POST">
<table class="table">
    <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
    </tr>
    <tr>
        <th>本文</th>
        <td>{{ form.text }}</td>
    </tr>
    <tr>
        <th>日付</th>
        <td>{{ form.date }}</td>
    </tr>
</table>
<button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}
</form>
{% endblock %}

project1/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
<tbody>
{% for day in day_list %}
<tr>
    <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
    <td>{{ day.date }}</td>
    <td>
    {% if user.is_superuser %}
    <a href="{% url 'diary:update' day.pk %}" target="_blank">更新</a>
    {% endif %}
    </td>
    <td>
    {% if user.is_superuser %}
    <a href="{% url 'diary:delete' day.pk %}" target="_blank">削除</a>
    {% endif %}
    </td>
</tr>
{% endfor %}
</tbody>
</table>

{% include 'diary/page3.html' %}

{% endblock %}

project1/diary/templates/diary/page1.html
<!-- 前の部分 -->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 次の部分 -->
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

project1/diary/templates/diary/page2.html
<!-- 前の部分 -->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<span>{{ num }}</span>
{% else %}
<a href ="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

<!-- 次の部分 -->
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

project1/diary/templates/diary/page3.html
<!-- 前の部分 -->
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

<!-- 次の部分 -->
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

project1/diary/templates/diary/page4.html
{% if page_obj.has_previous %}
«
{% endif %} {% for link_page in page_obj.paginator.page_range %} {% if link_page == page_obj.number %}
{{ link_page }}
{% else %}
{{ link_page }}
{% endif %} {% endfor %} {% if page_obj.has_next %}
»
{% endif %}